export const ADMINAUTH = "ADMINAUTH";

export const ADMINLOGIN = "ADMINLOGIN";

export const TEACHERLIST = "TEACHERLIST";

// Getting Course

export const GETQBOOKQUESTION = "GETQBOOKQUESTION";
export const GETQBANKQUESTION = "GETQBANKQUESTION";
export const GETWEEKLYQUESTION = "GETWEEKLYQUESTION";
export const GETMONTHLYQUESTION = "GETMONTHLYQUESTION";

export const GETQUESTIONVIAID = "GETQUESTIONVIAID";

export const REJECTEDGETQBOOKQUESTION = "REJECTEDGETQBOOKQUESTION";
export const REJECTEDGETQBANKQUESTION = "REJECTEDGETQBANKQUESTION";
export const REJECTEDGETWEEKLYQUESTION = "REJECTEDGETWEEKLYQUESTION";
export const REJECTEDGETMONTHLYQUESTION = "REJECTEDGETMONTHLYQUESTION";

export const CLEARQUESTION = "CLEARQUESTION";
